Repository RevenueCat/purchases-hybrid-common, pull requests merged in 2022-09, with the labels that each got.

#228 `Integration Tests`: added test for `promotionalOffer`
  ios/PurchasesHybridCommon/PurchasesHybridCommonIntegrationTests/CommonFunctionality+async.swift
  ios/PurchasesHybridCommon/PurchasesHybridCommonIntegrationTests/PurchasesHybridCommon.storekit
  ios/PurchasesHybridCommon/PurchasesHybridCommonIntegrationTests/StoreKitIntegrationTests.swift
  ios/PurchasesHybridCommon/PurchasesHybridCommonIntegrationTests/__Snapshots__/StoreKitIntegrationTests/SK1-testCanGetOfferings.1.json
  ios/PurchasesHybridCommon/PurchasesHybridCommonIntegrationTests/__Snapshots__/StoreKitIntegrationTests/SK1-testPromotionalOffer.1.json
  ios/PurchasesHybridCommon/PurchasesHybridCommonIntegrationTests/__Snapshots__/StoreKitIntegrationTests/SK2-testCanGetOfferings.1.json
  ios/PurchasesHybridCommon/PurchasesHybridCommonIntegrationTests/__Snapshots__/StoreKitIntegrationTests/SK2-testPromotionalOffer.1.json
Labels: test

#233 `CommonFunctionality`: fixed unknown error creation
  ios/PurchasesHybridCommon/PurchasesHybridCommon/CommonFunctionality.swift
Labels: fix

#237 Update Dangerfile to use repository
  Dangerfile
Labels: ci

#239 Remove upload of the PurchasesHybridCommon.framework
  .circleci/config.yml
  fastlane/Fastfile
Labels: ci

#240 Remove step from automatic-release to trigger Flutter update. Use its own job instead
  .circleci/config.yml
  fastlane/README.md
Labels: ci

#242 Automatic releases are missing the `AUTOMATIC` title
  fastlane/Fastfile
Labels: ci

#244 `IntegrationTests`: don't initialize `Purchases` until `SKTestSession` has been re-created
  ios/PurchasesHybridCommon/PurchasesHybridCommonIntegrationTests/StoreKitIntegrationTests.swift
Labels: test
