Repository RevenueCat/purchases-hybrid-common, pull requests merged in 2022-08, with the labels that each got.

#187 Product serialization: fixed snake_case and camelCase serialization inconsistency
  android/src/main/java/com/revenuecat/purchases/hybridcommon/mappers/StoreProductMapper.kt
  ios/PurchasesHybridCommon/PurchasesHybridCommon/SKProduct+HybridAdditions.swift
  ios/PurchasesHybridCommon/PurchasesHybridCommonIntegrationTests/__Snapshots__/StoreKitIntegrationTests/SK1-testCanGetOfferings.1.json
  ios/PurchasesHybridCommon/PurchasesHybridCommonIntegrationTests/__Snapshots__/StoreKitIntegrationTests/SK2-testCanGetOfferings.1.json
Labels: enhancement, breaking

#188 Release 4.0.0
  .version
  CHANGELOG.latest.md
  CHANGELOG.md
  PurchasesHybridCommon.podspec
  android/build.gradle
  android/gradle.properties
  ios/PurchasesHybridCommon/Info.plist
  ios/PurchasesHybridCommon/Podfile
  ios/PurchasesHybridCommon/PurchasesHybridCommonTests/Info.plist
Labels: next_release, breaking

#203 Release/4.1.2
  .version
  CHANGELOG.latest.md
  CHANGELOG.md
  PurchasesHybridCommon.podspec
  android/build.gradle
  android/gradle.properties
  ios/PurchasesHybridCommon/Info.plist
  ios/PurchasesHybridCommon/PurchasesHybridCommonTests/Info.plist
Labels: next_release

#204 Adds Danger
  .circleci/config.yml
  Dangerfile
  Gemfile
Labels: ci

#202 Release train
  .circleci/config.yml
  Gemfile.lock
  fastlane/Fastfile
Labels: ci

#199 `automaticAppleSearchAdsAttributionCollection`: changed implementation to call method directly
  ios/PurchasesHybridCommon/ObjCAPITester/RCHybridCommonAPITest.m
  ios/PurchasesHybridCommon/PurchasesHybridCommon.xcodeproj/project.pbxproj
  ios/PurchasesHybridCommon/PurchasesHybridCommon/CommonFunctionality.swift
  ios/PurchasesHybridCommon/PurchasesHybridCommonTests/PurchasesHybridCommonTests.swift
Labels: refactor

#208 `open_pr_upgrading_dependencies`: set `label` to `build`
  fastlane/Fastfile
Labels: ci

#207 Upgrade iOS to 4.10.2
  DEVELOPMENT.md
  PurchasesHybridCommon.podspec
  ios/PurchasesHybridCommon/Podfile
  ios/PurchasesHybridCommon/PurchasesHybridCommonTests/Mocks/MockPurchases.swift
Labels: build

#210 `IntegrationTests`: actually fail test if tests aren't configured
  ios/PurchasesHybridCommon/PurchasesHybridCommonIntegrationTests/BaseIntegrationTests.swift
Labels: test

#213 Replace build with dependencies on automatic upgrade PRs
  Dangerfile
  fastlane/Fastfile
Labels: ci

#218 Skip next version if there are no public changes
  Gemfile.lock
  fastlane/Fastfile
  fastlane/README.md
Labels: ci

#217 Fix CircleCI caches
  .circleci/config.yml
Labels: ci

#219 Add in missing attribution functions
  Gemfile.lock
  android/build.gradle
  android/src/main/java/com/revenuecat/purchases/hybridcommon/subscriberAttributes.kt
  ios/PurchasesHybridCommon/PurchasesHybridCommon/CommonFunctionality.swift
Labels: feat

#223 Adds hold jobs to manual trigger automatic dependency updates
  .circleci/config.yml
Labels: ci

#226 `purchase(productIdentifier:)` fixed SK2 implementation
  ios/PurchasesHybridCommon/PurchasesHybridCommon/CommonFunctionality.swift
  ios/PurchasesHybridCommon/PurchasesHybridCommonIntegrationTests/StoreKitIntegrationTests.swift
  ios/PurchasesHybridCommon/PurchasesHybridCommonIntegrationTests/__Snapshots__/StoreKitIntegrationTests/SK1-testCanPurchasePackage.1.json
  ios/PurchasesHybridCommon/PurchasesHybridCommonIntegrationTests/__Snapshots__/StoreKitIntegrationTests/SK1-testCanPurchaseProduct.1.json
  ios/PurchasesHybridCommon/PurchasesHybridCommonIntegrationTests/__Snapshots__/StoreKitIntegrationTests/SK2-testCanPurchasePackage.1.json
  ios/PurchasesHybridCommon/PurchasesHybridCommonIntegrationTests/__Snapshots__/StoreKitIntegrationTests/SK2-testCanPurchaseProduct.1.json
Labels: fix
