Repository RevenueCat/purchases-hybrid-common, pull requests merged in 2022-12, with the labels that each got.

#279 `Integration Tests`: enabled receipt fetch retry mechanism
  ios/PurchasesHybridCommon/PurchasesHybridCommonIntegrationTests/BaseIntegrationTests.swift
Labels: test

#283 Renames SKProduct and SKProductDiscount HybridAdditions files
  ios/PurchasesHybridCommon/PurchasesHybridCommon.xcodeproj/project.pbxproj
  ios/PurchasesHybridCommon/PurchasesHybridCommon/StoreProduct+HybridAdditions.swift
  ios/PurchasesHybridCommon/PurchasesHybridCommon/StoreProductDiscount+HybridAdditions.swift
Labels: refactor

#287 Update fastlane-plugin-revenuecat_internal to latest version
  Gemfile.lock
Labels: ci
