Repository RevenueCat/purchases-hybrid-common, pull requests merged in 2023-08, with the labels that each got.

#455 Move typescript interfaces to PHC
  .circleci/config.yml
  fastlane/Fastfile
  fastlane/README.md
  typescript/.eslintignore
  typescript/.eslintrc.cjs
  typescript/.gitignore
  typescript/.npmrc.SAMPLE
  typescript/package.json
  typescript/src/callbackTypes.ts
  typescript/src/customerInfo.ts
  typescript/src/enums.ts
  typescript/src/errors.ts
  typescript/src/index.ts
  typescript/src/offerings.ts
  typescript/src/purchasesConfiguration.ts
  typescript/tsconfig.json
Labels: refactor

#459 Add API tests to typescript interfaces
  .circleci/config.yml
  typescript/apitesters/customerInfo.ts
  typescript/apitesters/enums.ts
  typescript/apitesters/errors.ts
  typescript/apitesters/offerings.ts
  typescript/apitesters/tsconfig.json
  typescript/package.json
  typescript/src/index.ts
Labels: test

#471 Improvements typescript interfaces
  typescript/apitesters/customerInfo.ts
  typescript/apitesters/offerings.ts
  typescript/src/customerInfo.ts
  typescript/src/offerings.ts
Labels: refactor

#472 re-enable job to update PHC in unity
  .circleci/config.yml
Labels: ci

#485 Changed iOS `HybridAdditions` to `internal`
  ios/PurchasesHybridCommon/ObjCAPITester/RCHybridCommonDictionaryConversionsAPITest.m
  ios/PurchasesHybridCommon/PurchasesHybridCommon.xcodeproj/project.pbxproj
  ios/PurchasesHybridCommon/PurchasesHybridCommon/CustomerInfo+HybridAdditions.swift
  ios/PurchasesHybridCommon/PurchasesHybridCommon/EntitlementInfo+HybridAdditions.swift
  ios/PurchasesHybridCommon/PurchasesHybridCommon/EntitlementInfos+HybridAdditions.swift
  ios/PurchasesHybridCommon/PurchasesHybridCommon/NonSubscriptionTransaction+HybridAdditions.swift
  ios/PurchasesHybridCommon/PurchasesHybridCommon/Offerings+HybridAdditions.swift
  ios/PurchasesHybridCommon/PurchasesHybridCommon/Package+HybridAdditions.swift
  ios/PurchasesHybridCommon/PurchasesHybridCommon/StoreProduct+HybridAdditions.swift
  ios/PurchasesHybridCommon/PurchasesHybridCommon/StoreProductDiscount+HybridAdditions.swift
  ios/PurchasesHybridCommon/PurchasesHybridCommon/StoreTransaction+HybridAdditions.swift
  ios/PurchasesHybridCommon/PurchasesHybridCommonTests/StoreProduct+HybridAdditionsTests.swift
  ios/PurchasesHybridCommon/PurchasesHybridCommonTests/StoreProductDiscount+HybridAdditionsTests.swift
Labels: breaking

#486 Release/6.0.0
  .version
  CHANGELOG.latest.md
  CHANGELOG.md
  PurchasesHybridCommon.podspec
  android/build.gradle
  android/gradle.properties
  ios/PurchasesHybridCommon/Info.plist
  ios/PurchasesHybridCommon/PurchasesHybridCommonTests/Info.plist
  typescript/package.json
Labels: next_release

#487 Expose `CommonFunctionality.encode(customerInfo:)`
  ios/PurchasesHybridCommon/ObjCAPITester/RCHybridCommonAPITest.m
  ios/PurchasesHybridCommon/PurchasesHybridCommon/CommonFunctionality.swift
  ios/PurchasesHybridCommon/PurchasesHybridCommon/CustomerInfo+HybridAdditions.swift
  ios/PurchasesHybridCommon/PurchasesHybridCommonTests/CustomerInfo+HybridAdditionsTests.swift
Labels: feat
