Repository RevenueCat/purchases-hybrid-common, pull requests merged in 2023-10, with the labels that each got.

#512 Add `product_plan_identifier` to `EntitlementInfo` model
  android/src/main/java/com/revenuecat/purchases/hybridcommon/mappers/EntitlementInfoMapper.kt
  android/src/test/java/com/revenuecat/purchases/hybridcommon/mappers/EntitlementInfoMapperTests.kt
  ios/PurchasesHybridCommon/PurchasesHybridCommon/EntitlementInfo+HybridAdditions.swift
  ios/PurchasesHybridCommon/PurchasesHybridCommonIntegrationTests/__Snapshots__/StoreKitIntegrationTests/SK1-testCanPurchasePackage.1.json
  ios/PurchasesHybridCommon/PurchasesHybridCommonIntegrationTests/__Snapshots__/StoreKitIntegrationTests/SK1-testCanPurchaseProduct.1.json
  ios/PurchasesHybridCommon/PurchasesHybridCommonIntegrationTests/__Snapshots__/StoreKitIntegrationTests/SK2-testCanPurchasePackage.1.json
  ios/PurchasesHybridCommon/PurchasesHybridCommonIntegrationTests/__Snapshots__/StoreKitIntegrationTests/SK2-testCanPurchaseProduct.1.json
  typescript/apitesters/customerInfo.ts
  typescript/src/customerInfo.ts
Labels: fix

#515 Add documentation for productType field in StoreProduct in typescript
  typescript/src/offerings.ts
Labels: docs

#511 URL(string:): add clarifying comment
  ios/PurchasesHybridCommon/PurchasesHybridCommon/CommonFunctionality.swift
Labels: docs

#520 Update android to 7.0
  android/build.gradle
  android/src/main/java/com/revenuecat/purchases/hybridcommon/common.kt
Labels: breaking

#521 `CI`: run iOS 17 tests
  .circleci/config.yml
Labels: ci

#506 Temporarily remode DEFERRED proration mode in preparation for upgrade to Billing Client 6
  typescript/apitesters/enums.ts
  typescript/src/offerings.ts
Labels: breaking

#510 Add in app messages API support
  android/src/main/java/com/revenuecat/purchases/hybridcommon/common.kt
  android/src/test/java/apitests/java/CommonApiTests.java
  android/src/test/java/apitests/kotlin/com/revenuecat/purchases/hybridcommon/CommonApiTests.kt
  ios/PurchasesHybridCommon/ObjCAPITester/RCPurchases+HybridAdditionsAPITest.m
  ios/PurchasesHybridCommon/PurchasesHybridCommon/CommonFunctionality.swift
  ios/PurchasesHybridCommon/PurchasesHybridCommon/Purchases+HybridAdditions.swift
  typescript/apitesters/enums.ts
  typescript/src/enums.ts
  typescript/src/purchasesConfiguration.ts
Labels: breaking, feat

#523 Improve breaking changes changelog for 7.0
  CHANGELOG.latest.md
  CHANGELOG.md
Labels: docs

#528 Add `product_plan_identifier` to `EntitlementInfo` in iOS
  ios/PurchasesHybridCommon/PurchasesHybridCommon/EntitlementInfo+HybridAdditions.swift
Labels: feat

#530 `CI`: fixed iOS 17 simulator
  .circleci/config.yml
Labels: ci

#536 Use RevenueCat orb for bundle install cache
  .circleci/config.yml
Labels: ci
