Repository RevenueCat/purchases-hybrid-common, pull requests merged in 2023-01, with the labels that each got.

#284 Add StoreProduct Android Tests
  android/src/test/java/com/revenuecat/purchases/hybridcommon/mappers/StoreProductIntroPriceMapperTests.kt
  android/src/test/java/com/revenuecat/purchases/hybridcommon/mappers/StoreProductMapperTests.kt
Labels: test

#288 Fix warnings when running pod install
  ios/PurchasesHybridCommon/PurchasesHybridCommon.xcodeproj/project.pbxproj
Labels: build

#285 Add StoreProduct mapper iOS tests
  ios/PurchasesHybridCommon/PurchasesHybridCommon.xcodeproj/project.pbxproj
  ios/PurchasesHybridCommon/PurchasesHybridCommonTests/StoreProduct+HybridAdditionsTests.swift
  ios/PurchasesHybridCommon/PurchasesHybridCommonTests/StoreProductDiscount+HybridAdditionsTests.swift
Labels: test

#286 Adds subscriptionPeriod
  android/src/main/java/com/revenuecat/purchases/hybridcommon/mappers/StoreProductMapper.kt
  android/src/test/java/com/revenuecat/purchases/hybridcommon/mappers/StoreProductMapperTests.kt
  ios/PurchasesHybridCommon/PurchasesHybridCommon/StoreProduct+HybridAdditions.swift
  ios/PurchasesHybridCommon/PurchasesHybridCommonIntegrationTests/__Snapshots__/StoreKitIntegrationTests/SK1-testCanGetOfferings.1.json
  ios/PurchasesHybridCommon/PurchasesHybridCommonIntegrationTests/__Snapshots__/StoreKitIntegrationTests/SK2-testCanGetOfferings.1.json
  ios/PurchasesHybridCommon/PurchasesHybridCommonTests/StoreProduct+HybridAdditionsTests.swift
Labels: feat

#293 Update secring
  android/secring.gpg
Labels: build

#294 `CommonFunctionality.sharedInstance`: changed type to `PurchasesType & PurchasesSwiftType`
  ios/PurchasesHybridCommon/PurchasesHybridCommon/CommonFunctionality.swift
Labels: refactor

#290 Add `beginRefundRequest` APIs in iOS
  ios/PurchasesHybridCommon/ObjCAPITester/RCHybridCommonAPITest.m
  ios/PurchasesHybridCommon/PurchasesHybridCommon/CommonFunctionality.swift
  ios/PurchasesHybridCommon/PurchasesHybridCommonTests/Mocks/MockPurchases.swift
  ios/PurchasesHybridCommon/PurchasesHybridCommonTests/PurchasesHybridCommonTests.swift
Labels: feat

#296 Update Gemfile.lock
  Gemfile.lock
Labels: ci

#297 Added `CommonFunctionality.setLogLevel`
  ios/PurchasesHybridCommon/ObjCAPITester/RCHybridCommonAPITest.m
  ios/PurchasesHybridCommon/PurchasesHybridCommon/CommonFunctionality.swift
  ios/PurchasesHybridCommon/PurchasesHybridCommon/Purchases+HybridAdditions.swift
  ios/PurchasesHybridCommon/PurchasesHybridCommonTests/PurchasesHybridAdditionsTests.swift
  ios/PurchasesHybridCommon/PurchasesHybridCommonTests/PurchasesHybridCommonTests.swift
Labels: feat

#302 Upgrade AGP to 7.4.0
  android/build.gradle
  android/gradle/wrapper/gradle-wrapper.properties
Labels: build

#303 `DEVELOPMENT.md`: added section for pointing to local `purchases-android`
  DEVELOPMENT.md
Labels: docs

#301 Android: added `CommonKt.setLogLevel`
  android/src/main/java/com/revenuecat/purchases/hybridcommon/common.kt
  android/src/test/java/apitests/java/CommonApiTests.java
  android/src/test/java/apitests/kotlin/com/revenuecat/purchases/hybridcommon/CommonApiTests.kt
Labels: feat

#307 Adds setLogHandler
  android/src/main/java/com/revenuecat/purchases/hybridcommon/common.kt
  android/src/main/java/com/revenuecat/purchases/hybridcommon/mappers/LogHandlerWithMapping.kt
  android/src/test/java/apitests/java/CommonApiTests.java
  android/src/test/java/apitests/kotlin/com/revenuecat/purchases/hybridcommon/CommonApiTests.kt
  android/src/test/java/com/revenuecat/purchases/hybridcommon/CommonKtTests.kt
  ios/PurchasesHybridCommon/ObjCAPITester/RCHybridCommonAPITest.m
  ios/PurchasesHybridCommon/PurchasesHybridCommon/CommonFunctionality.swift
  ios/PurchasesHybridCommon/PurchasesHybridCommonTests/PurchasesHybridCommonTests.swift
Labels: feat

#312 Create dependabot.yml to automatically update Gemfile
  .github/dependabot.yml
Labels: dependencies

#314 Update dependabot.yml package system
  .github/dependabot.yml
Labels: ci

#316 Fix for dependabot issue parsing Gemfile
  Gemfile
Labels: ci
