Repository RevenueCat/purchases-hybrid-common, pull requests merged in 2023-09, with the labels that each got.

#494 Support deploying separate ESNext typescript package
  .circleci/config.yml
  fastlane/Fastfile
  fastlane/README.md
Labels: build

#497 Trigger automatic PHC updates in Capacitor plugin
  .circleci/config.yml
Labels: build

#507 Add product type to typescript types
  typescript/apitesters/offerings.ts
  typescript/src/offerings.ts
Labels: feat

#508 fix proxyURL not crashing if invalid url is passed
  ios/PurchasesHybridCommon/PurchasesHybridCommon/CommonFunctionality.swift
Labels: test
