Repository RevenueCat/purchases-hybrid-common, pull requests merged in 2023-03, with the labels that each got.

#346 `CommonFunctionality.setLogHandler`: fixed docstring warning
  ios/PurchasesHybridCommon/PurchasesHybridCommon/CommonFunctionality.swift
Labels: docs

#345 `EntitlementInfo`: fixed `unsubscribeDetectedAt` typo
  ios/PurchasesHybridCommon/PurchasesHybridCommon/EntitlementInfo+HybridAdditions.swift
  ios/PurchasesHybridCommon/PurchasesHybridCommonIntegrationTests/__Snapshots__/StoreKitIntegrationTests/SK1-testCanPurchasePackage.1.json
  ios/PurchasesHybridCommon/PurchasesHybridCommonIntegrationTests/__Snapshots__/StoreKitIntegrationTests/SK1-testCanPurchaseProduct.1.json
  ios/PurchasesHybridCommon/PurchasesHybridCommonIntegrationTests/__Snapshots__/StoreKitIntegrationTests/SK2-testCanPurchasePackage.1.json
  ios/PurchasesHybridCommon/PurchasesHybridCommonIntegrationTests/__Snapshots__/StoreKitIntegrationTests/SK2-testCanPurchaseProduct.1.json
Labels: fix

#357 [BC5] Temporarily remove Unity IAP from tests and release until its supported
  .circleci/config.yml
  android/build.gradle
  fastlane/Fastfile
Labels: build

#355 [BC5] Adds PREPAID_SUBSCRIPTION to mapProductType
  android/src/main/java/com/revenuecat/purchases/hybridcommon/mappers/StoreProductMapper.kt
  android/src/test/java/com/revenuecat/purchases/hybridcommon/CommonKtTests.kt
  android/src/test/java/com/revenuecat/purchases/hybridcommon/mappers/StoreProductMapperTests.kt
Labels: feat

#356 [BC5] Add isPersonalizedPrice to purchaseProduct and purchasePackage
  android/src/main/java/com/revenuecat/purchases/hybridcommon/common.kt
  android/src/test/java/apitests/java/CommonApiTests.java
  android/src/test/java/apitests/kotlin/com/revenuecat/purchases/hybridcommon/CommonApiTests.kt
  android/src/test/java/com/revenuecat/purchases/hybridcommon/CommonKtTests.kt
Labels: feat

#364 [WIP] Release/5.0.0-beta.1
  .version
  CHANGELOG.latest.md
  CHANGELOG.md
  PurchasesHybridCommon.podspec
  android/build.gradle
  android/gradle.properties
  ios/PurchasesHybridCommon/Info.plist
  ios/PurchasesHybridCommon/PurchasesHybridCommonTests/Info.plist
Labels: next_release
