Repository RevenueCat/purchases-hybrid-common, pull requests merged in 2023-06, with the labels that each got.

#418 Fix tests by removing mocking of currency formatters which weren't ne…
  android/build.gradle
  android/src/test/java/com/revenuecat/purchases/hybridcommon/CommonKtTests.kt
  android/src/test/java/com/revenuecat/purchases/hybridcommon/MockUtils.kt
  android/src/test/java/com/revenuecat/purchases/hybridcommon/mappers/StoreProductIntroPriceMapperTests.kt
Labels: test

#419 Add offering metadata
  android/src/main/java/com/revenuecat/purchases/hybridcommon/mappers/OfferingsMapper.kt
  android/src/test/java/com/revenuecat/purchases/hybridcommon/CommonKtTests.kt
Labels: feat

#422 `MockStoreProduct`: fixed `Sendable` warnings
  ios/PurchasesHybridCommon/PurchasesHybridCommonTests/Offering+HybridAdditionsTests.swift
Labels: test

#427 Release/5.0.0-rc.1
  .version
  CHANGELOG.latest.md
  CHANGELOG.md
  PurchasesHybridCommon.podspec
  android/build.gradle
  android/gradle.properties
Labels: next_release

#428 Add isPrepaid to subscription option mapper
  android/src/main/java/com/revenuecat/purchases/hybridcommon/mappers/StoreProductMapper.kt
  android/src/test/java/com/revenuecat/purchases/hybridcommon/mappers/StoreProductMapperTests.kt
Labels: feat

#430 Release/5.0.0
  .version
  CHANGELOG.latest.md
  CHANGELOG.md
  PurchasesHybridCommon.podspec
  android/build.gradle
  android/gradle.properties
Labels: next_release

#446 Android: retrieve free trial period from the free phase
  android/src/main/java/com/revenuecat/purchases/hybridcommon/mappers/StoreProductMapper.kt
  android/src/test/java/com/revenuecat/purchases/hybridcommon/mappers/StoreProductIntroPriceMapperTests.kt
Labels: fix

#448 CI: wait until pods have been pushed to trigger dependent updates
  .circleci/config.yml
Labels: ci

#450 `.composite-enable`: fixed file reference
  android/settings.gradle
Labels: build

#449 Fix free trial and intro price to derive from defaultOption
  android/src/main/java/com/revenuecat/purchases/hybridcommon/mappers/StoreProductMapper.kt
  android/src/test/java/com/revenuecat/purchases/hybridcommon/mappers/StoreProductIntroPriceMapperTests.kt
Labels: fix

#445 Remove latestDependencies variant
  android/build.gradle
  android/gradle.properties
Labels: build, ci
