Repository RevenueCat/purchases-hybrid-common, pull requests merged in 2023-04, with the labels that each got.

#365 [BC5] Rename `Period` fields to `unit` and `value`
  android/src/main/java/com/revenuecat/purchases/hybridcommon/mappers/StoreProductMapper.kt
  android/src/test/java/com/revenuecat/purchases/hybridcommon/mappers/StoreProductMapperTests.kt
Labels: breaking

#366 [BC5] Fix purchaseProduct to work with productIdentifiers with base plans
  android/src/main/java/com/revenuecat/purchases/hybridcommon/common.kt
  android/src/test/java/apitests/java/CommonApiTests.java
  android/src/test/java/apitests/kotlin/com/revenuecat/purchases/hybridcommon/CommonApiTests.kt
  android/src/test/java/com/revenuecat/purchases/hybridcommon/CommonKtTests.kt
Labels: feat, fix

#367 Release/5.0.0-beta.2
  .version
  CHANGELOG.latest.md
  CHANGELOG.md
  PurchasesHybridCommon.podspec
  android/build.gradle
  android/gradle.properties
Labels: next_release

#369 [BC5] Add `iso8601` to `Period` for subscription option pricing phases
  android/src/main/java/com/revenuecat/purchases/hybridcommon/mappers/StoreProductMapper.kt
  android/src/test/java/com/revenuecat/purchases/hybridcommon/mappers/StoreProductIntroPriceMapperTests.kt
  android/src/test/java/com/revenuecat/purchases/hybridcommon/mappers/StoreProductMapperTests.kt
Labels: feat

#371 Add platform check,`OfferPaymentMode`, and `presentedOfferingIdentifier`
  android/build.gradle
  android/src/main/java/com/revenuecat/purchases/hybridcommon/common.kt
  android/src/main/java/com/revenuecat/purchases/hybridcommon/mappers/StoreProductMapper.kt
  android/src/test/java/apitests/java/CommonApiTests.java
  android/src/test/java/apitests/kotlin/com/revenuecat/purchases/hybridcommon/CommonApiTests.kt
  android/src/test/java/com/revenuecat/purchases/hybridcommon/CommonKtTests.kt
  android/src/test/java/com/revenuecat/purchases/hybridcommon/mappers/StoreProductMapperTests.kt
Labels: fix

#372 Release/5.0.0-beta.4
  .version
  CHANGELOG.latest.md
  CHANGELOG.md
  PurchasesHybridCommon.podspec
  android/build.gradle
  android/gradle.properties
Labels: next_release

#374 `CommonFunctionality.beginRefundRequest`: available on Catalyst
  ios/PurchasesHybridCommon/PurchasesHybridCommon/CommonFunctionality.swift
Labels: build

#376 [BC5] Rename `productCategory` to `productType` and `productType` to `productSubtype`
  android/src/main/java/com/revenuecat/purchases/hybridcommon/mappers/StoreProductMapper.kt
  android/src/test/java/com/revenuecat/purchases/hybridcommon/mappers/StoreProductMapperTests.kt
Labels: refactor

#384 [BC5] Use new mapped product type values for `purchaseProduct()` and `getProductInfo()`
  android/src/main/java/com/revenuecat/purchases/hybridcommon/common.kt
  android/src/main/java/com/revenuecat/purchases/hybridcommon/mappers/StoreProductMapper.kt
  android/src/test/java/com/revenuecat/purchases/hybridcommon/CommonKtTests.kt
Labels: refactor

#386 [BC5] Reverting back to 5.0.0-beta.4
  android/src/main/java/com/revenuecat/purchases/hybridcommon/common.kt
  android/src/main/java/com/revenuecat/purchases/hybridcommon/mappers/StoreProductMapper.kt
  android/src/test/java/com/revenuecat/purchases/hybridcommon/CommonKtTests.kt
  android/src/test/java/com/revenuecat/purchases/hybridcommon/mappers/StoreProductMapperTests.kt
  ios/PurchasesHybridCommon/PurchasesHybridCommon/StoreProduct+HybridAdditions.swift
  ios/PurchasesHybridCommon/PurchasesHybridCommonIntegrationTests/__Snapshots__/StoreKitIntegrationTests/SK1-testCanGetOfferings.1.json
  ios/PurchasesHybridCommon/PurchasesHybridCommonIntegrationTests/__Snapshots__/StoreKitIntegrationTests/SK2-testCanGetOfferings.1.json
  ios/PurchasesHybridCommon/PurchasesHybridCommonTests/StoreProduct+HybridAdditionsTests.swift
Labels: breaking

#387 [BC5] Add product category support in `getProductInfo()` and `purchaseProduct()`
  android/src/main/java/com/revenuecat/purchases/hybridcommon/common.kt
  android/src/main/java/com/revenuecat/purchases/hybridcommon/mappers/StoreProductMapper.kt
  android/src/test/java/com/revenuecat/purchases/hybridcommon/CommonKtTests.kt
Labels: feat

#388 Release/5.0.0-beta.6
  .version
  CHANGELOG.latest.md
  CHANGELOG.md
  PurchasesHybridCommon.podspec
  android/build.gradle
  android/gradle.properties
Labels: next_release
