Repository RevenueCat/purchases-hybrid-common, pull requests merged in 2023-05, with the labels that each got.

#405 Xcode 14.3: fixed warning
  ios/PurchasesHybridCommon/PurchasesHybridCommon/CommonFunctionality.swift
Labels: refactor

#411 Remove `watchOS` as a supported platform
  .circleci/config.yml
  PurchasesHybridCommon.podspec
  ios/PurchasesHybridCommon/PurchasesHybridCommon.xcodeproj/project.pbxproj
  ios/PurchasesHybridCommon/PurchasesHybridCommon.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: feat

#415 Add metadata to offering for iOS
  ios/PurchasesHybridCommon/PurchasesHybridCommon.xcodeproj/project.pbxproj
  ios/PurchasesHybridCommon/PurchasesHybridCommon/Offering+HybridAdditions.swift
  ios/PurchasesHybridCommon/PurchasesHybridCommonIntegrationTests/__Snapshots__/StoreKitIntegrationTests/SK1-testCanGetOfferings.1.json
  ios/PurchasesHybridCommon/PurchasesHybridCommonIntegrationTests/__Snapshots__/StoreKitIntegrationTests/SK2-testCanGetOfferings.1.json
  ios/PurchasesHybridCommon/PurchasesHybridCommonTests/Offering+HybridAdditionsTests.swift
Labels: feat

#417 Makes pushing to Cocoapods its own job
  .circleci/config.yml
  fastlane/Fastfile
Labels: ci
