Repository RevenueCat/purchases-hybrid-common, pull requests merged in 2023-12, with the labels that each got.

#591 Merge dependency-update workflows and fix automatic-release being triggered when executing action
  .circleci/config.yml
Labels: ci

#601 Update paywalls with latest main
  .circleci/config.yml
  .version
  CHANGELOG.latest.md
  CHANGELOG.md
  DEVELOPMENT.md
  Gemfile.lock
  PurchasesHybridCommon.podspec
  android/build.gradle
  android/gradle.properties
  ios/PurchasesHybridCommon/Info.plist
  ios/PurchasesHybridCommon/Podfile
  ios/PurchasesHybridCommon/Podfile.lock
  ios/PurchasesHybridCommon/PurchasesHybridCommonTests/Info.plist
  typescript/package.json
Labels: refactor

#586 Paywalls: Expose delegate in PaywallProxy to receive events
  ios/PurchasesHybridCommon/PurchasesHybridCommon/PaywallProxy.swift
Labels: RevenueCatUI

#602 Add PaywallFragmentViewModel to share data with caller fragment/activity
  android/src/main/java/com/revenuecat/purchases/hybridcommon/PaywallFragment.kt
  android/src/main/java/com/revenuecat/purchases/hybridcommon/PaywallFragmentViewModel.kt
  android/src/main/java/com/revenuecat/purchases/hybridcommon/PaywallHelpers.kt
  android/src/main/java/com/revenuecat/purchases/hybridcommon/PaywallResultListener.kt
Labels: RevenueCatUI

#605 Release/8.1.3-beta.5
  .version
  CHANGELOG.latest.md
  CHANGELOG.md
  PurchasesHybridCommon.podspec
  android/gradle.properties
  fastlane/Fastfile
  typescript/package.json
Labels: next_release

#608 Remove core-ktx dependency
  android/api-tests/build.gradle.kts
  android/gradle/libs.versions.toml
  android/hybridcommon-ui/build.gradle.kts
  android/hybridcommon/build.gradle.kts
Labels: dependencies

#609 Update purchases android to 7.3.0
  android/gradle/libs.versions.toml
Labels: RevenueCatUI

#607 Trim version file contents
  fastlane/Fastfile
Labels: ci

#610 Release/8.1.3-beta.6
  .version
  CHANGELOG.latest.md
  CHANGELOG.md
  PurchasesHybridCommon.podspec
  android/gradle.properties
  typescript/package.json
Labels: next_release

#606 Add shouldDisplayDismissButton
  android/api-tests/src/test/java/com/revenuecat/apitests/java/PaywallApiTests.java
  android/api-tests/src/test/java/com/revenuecat/apitests/kotlin/PaywallApiTests.kt
  android/hybridcommon-ui/src/main/java/com/revenuecat/purchases/hybridcommon/ui/PaywallFragment.kt
  android/hybridcommon-ui/src/main/java/com/revenuecat/purchases/hybridcommon/ui/PaywallHelpers.kt
  ios/PurchasesHybridCommon/ObjCAPITester/RCPaywallProxyAPITest.m
  ios/PurchasesHybridCommon/PurchasesHybridCommon/PaywallProxy.swift
Labels: RevenueCatUI

#612 Add offering parameter for launching paywalls
  android/api-tests/src/test/java/com/revenuecat/apitests/java/PaywallApiTests.java
  android/api-tests/src/test/java/com/revenuecat/apitests/kotlin/PaywallApiTests.kt
  android/hybridcommon-ui/src/main/java/com/revenuecat/purchases/hybridcommon/ui/PaywallFragment.kt
  android/hybridcommon-ui/src/main/java/com/revenuecat/purchases/hybridcommon/ui/PaywallHelpers.kt
  ios/PurchasesHybridCommon/PurchasesHybridCommon/PaywallProxy.swift
Labels: RevenueCatUI

#617 Update paywalls branch with latest main
  .version
  CHANGELOG.latest.md
  CHANGELOG.md
  DEVELOPMENT.md
  PurchasesHybridCommon.podspec
  android/gradle/libs.versions.toml
  fastlane/Fastfile
  ios/PurchasesHybridCommon/Info.plist
  ios/PurchasesHybridCommon/Podfile
  ios/PurchasesHybridCommon/Podfile.lock
  ios/PurchasesHybridCommon/PurchasesHybridCommonTests/Info.plist
Labels: RevenueCatUI

#620 Release 8.10.0-beta.7
  .version
  CHANGELOG.latest.md
  CHANGELOG.md
  PurchasesHybridCommon.podspec
  android/gradle.properties
  ios/PurchasesHybridCommon/Info.plist
  ios/PurchasesHybridCommon/PurchasesHybridCommonTests/Info.plist
  typescript/package.json
Labels: next_release, RevenueCatUI

#622 Fix dismiss button not showing in Android when not specified
  android/hybridcommon-ui/src/main/java/com/revenuecat/purchases/hybridcommon/ui/PaywallFragment.kt
Labels: fix, RevenueCatUI

#615 Add lefthook to configure a pre-push hook that runs detekt
  .lefthook/pre-push/detekt.sh
  Gemfile
  Gemfile.lock
  lefthook.yml
Labels: style, android
