Repository RevenueCat/purchases-hybrid-common, pull requests merged in 2023-11, with the labels that each got.

#555 release/2.0.2
  .circleci/config.yml
  PurchasesHybridCommon.podspec
  android/build.gradle
  android/gradle.properties
  ios/PurchasesHybridCommon/Info.plist
  ios/PurchasesHybridCommon/Podfile
  ios/PurchasesHybridCommon/Podfile.lock
  ios/PurchasesHybridCommon/PurchasesHybridCommonTests/Info.plist
Labels: next_release

#554 release/1.11.3
  PurchasesHybridCommon.podspec
  android/build.gradle
  android/gradle.properties
  ios/PurchasesHybridCommon/Info.plist
  ios/PurchasesHybridCommon/Podfile
  ios/PurchasesHybridCommon/Podfile.lock
  ios/PurchasesHybridCommon/PurchasesHybridCommon/RCPurchases+HybridAdditions.h
  ios/PurchasesHybridCommon/PurchasesHybridCommon/RCPurchases+HybridAdditions.m
  ios/PurchasesHybridCommon/PurchasesHybridCommonTests/Info.plist
Labels: next_release

#558 Fix deploy android circleci job
  .sdkmanrc
Labels: build

#559 Improve circleci deploy automation
  .circleci/config.yml
Labels: ci

#451 `Trusted Entitlements`: add support for setting `VerificationMode`
  android/src/main/java/com/revenuecat/purchases/hybridcommon/common.kt
  android/src/test/java/apitests/java/CommonApiTests.java
  android/src/test/java/apitests/kotlin/com/revenuecat/purchases/hybridcommon/CommonApiTests.kt
  android/src/test/java/com/revenuecat/purchases/hybridcommon/ConfiguringUnitTests.kt
  android/src/test/java/com/revenuecat/purchases/hybridcommon/MockUtils.kt
  android/src/test/java/com/revenuecat/purchases/hybridcommon/PurchasesPeriodTests.kt
  ios/PurchasesHybridCommon/ObjCAPITester/RCPurchases+HybridAdditionsAPITest.m
  ios/PurchasesHybridCommon/PurchasesHybridCommon.xcodeproj/project.pbxproj
  ios/PurchasesHybridCommon/PurchasesHybridCommon/EntitlementVerificationMode+HybridAdditions.swift
  ios/PurchasesHybridCommon/PurchasesHybridCommon/Purchases+HybridAdditions.swift
  ios/PurchasesHybridCommon/PurchasesHybridCommonTests/PurchasesHybridAdditionsTests.swift
  typescript/apitesters/enums.ts
  typescript/src/enums.ts
  typescript/src/purchasesConfiguration.ts
Labels: feat, android, iOS

#569 `Trusted Entitlements`: Add `verification` field to EntitlementInfo and EntitlementInfos
  android/src/main/java/com/revenuecat/purchases/hybridcommon/mappers/EntitlementInfoMapper.kt
  android/src/main/java/com/revenuecat/purchases/hybridcommon/mappers/EntitlementInfosMapper.kt
  android/src/test/java/com/revenuecat/purchases/hybridcommon/mappers/EntitlementInfoMapperTests.kt
  ios/PurchasesHybridCommon/PurchasesHybridCommon/EntitlementInfo+HybridAdditions.swift
  ios/PurchasesHybridCommon/PurchasesHybridCommon/EntitlementInfos+HybridAdditions.swift
  ios/PurchasesHybridCommon/PurchasesHybridCommonIntegrationTests/__Snapshots__/StoreKitIntegrationTests/SK1-testCanPurchasePackage.1.json
  ios/PurchasesHybridCommon/PurchasesHybridCommonIntegrationTests/__Snapshots__/StoreKitIntegrationTests/SK1-testCanPurchaseProduct.1.json
  ios/PurchasesHybridCommon/PurchasesHybridCommonIntegrationTests/__Snapshots__/StoreKitIntegrationTests/SK1-testLogInAndLogOut.1.json
  ios/PurchasesHybridCommon/PurchasesHybridCommonIntegrationTests/__Snapshots__/StoreKitIntegrationTests/SK1-testLogInAndLogOut.2.json
  ios/PurchasesHybridCommon/PurchasesHybridCommonIntegrationTests/__Snapshots__/StoreKitIntegrationTests/SK2-testCanPurchasePackage.1.json
  ios/PurchasesHybridCommon/PurchasesHybridCommonIntegrationTests/__Snapshots__/StoreKitIntegrationTests/SK2-testCanPurchaseProduct.1.json
  ios/PurchasesHybridCommon/PurchasesHybridCommonIntegrationTests/__Snapshots__/StoreKitIntegrationTests/SK2-testLogInAndLogOut.1.json
  ios/PurchasesHybridCommon/PurchasesHybridCommonIntegrationTests/__Snapshots__/StoreKitIntegrationTests/SK2-testLogInAndLogOut.2.json
  ios/PurchasesHybridCommon/PurchasesHybridCommonTests/EntitlementInfo+HybridAdditionsTests.swift
  typescript/apitesters/customerInfo.ts
  typescript/apitesters/enums.ts
  typescript/src/customerInfo.ts
  typescript/src/enums.ts
Labels: feat

#572 Fix breaking change in objc in 7.4.0
  ios/PurchasesHybridCommon/ObjCAPITester/RCPurchases+HybridAdditionsAPITest.m
  ios/PurchasesHybridCommon/PurchasesHybridCommon/Purchases+HybridAdditions.swift
Labels: fix

#574 Fix entitlement verification name typo
  typescript/apitesters/purchasesConfiguration.ts
  typescript/src/purchasesConfiguration.ts
Labels: breaking, fix

#578 Release/8.0.0
  .version
  CHANGELOG.latest.md
  CHANGELOG.md
  PurchasesHybridCommon.podspec
  android/build.gradle
  android/gradle.properties
  ios/PurchasesHybridCommon/Info.plist
  ios/PurchasesHybridCommon/PurchasesHybridCommonTests/Info.plist
  typescript/package.json
Labels: next_release
