Repository RevenueCat/purchases-hybrid-common, pull requests merged in 2024-12, with the labels that each got.

#979 Change dependency-update job to macos machine
  .circleci/config.yml
Labels: pr:other

#987 Support Web Redemption Links
  PurchasesHybridCommon.podspec
  PurchasesHybridCommonUI.podspec
  android/gradle/libs.versions.toml
  android/hybridcommon/src/main/java/com/revenuecat/purchases/hybridcommon/common.kt
  ios/PurchasesHybridCommon/Podfile
  ios/PurchasesHybridCommon/Podfile.lock
  ios/PurchasesHybridCommon/PurchasesHybridCommon/CommonFunctionality.swift
  ios/PurchasesHybridCommon/PurchasesHybridCommonTests/EntitlementInfo+HybridAdditionsTests.swift
  typescript/api-report/purchases-typescript-internal.api.md
  typescript/src/index.ts
  typescript/src/webRedemption.ts
Labels: pr:feat

#990 Add empty `NSPrivacyCollectedDataTypes`
  ios/PurchasesHybridCommon/PurchasesHybridCommon/PrivacyInfo.xcprivacy
Labels: pr:fix

#997 Updates `Package.swift` and `Package.resolved`
  Package.resolved
  Package.swift
Labels: pr:fix

#995 Add diagnostics support
  android/api-tests/src/test/java/com/revenuecat/apitests/java/CommonApiTests.java
  android/api-tests/src/test/java/com/revenuecat/apitests/kotlin/CommonApiTests.kt
  android/hybridcommon/src/main/java/com/revenuecat/purchases/hybridcommon/common.kt
  ios/PurchasesHybridCommon/ObjCAPITester/RCPurchases+HybridAdditionsAPITest.m
  ios/PurchasesHybridCommon/PurchasesHybridCommon/Purchases+HybridAdditions.swift
  typescript/api-report/purchases-typescript-internal.api.md
  typescript/src/purchasesConfiguration.ts
Labels: pr:feat

#1001 Update docstring for diagnostics to clarify meaning
  typescript/src/purchasesConfiguration.ts
Labels: pr:other
