Repository RevenueCat/purchases-hybrid-common, pull requests merged in 2024-01, with the labels that each got.

#624 Add `createFooterPaywallView` to `PaywallProxy`
  ios/PurchasesHybridCommon/PurchasesHybridCommon/PaywallProxy.swift
Labels: RevenueCatUI

#625 Release 8.10.0-beta.8
  .version
  CHANGELOG.latest.md
  CHANGELOG.md
  PurchasesHybridCommon.podspec
  android/gradle.properties
  typescript/package.json
Labels: RevenueCatUI

#628 Support result present paywall
  android/api-tests/src/test/java/com/revenuecat/apitests/java/PaywallApiTests.java
  android/api-tests/src/test/java/com/revenuecat/apitests/kotlin/PaywallApiTests.kt
  android/gradle/libs.versions.toml
  android/hybridcommon-ui/src/main/java/com/revenuecat/purchases/hybridcommon/ui/PaywallFragment.kt
  android/hybridcommon-ui/src/main/java/com/revenuecat/purchases/hybridcommon/ui/PaywallResultExtensions.kt
  android/hybridcommon-ui/src/main/java/com/revenuecat/purchases/hybridcommon/ui/PaywallResultListener.kt
  ios/PurchasesHybridCommon/ObjCAPITester/RCPaywallProxyAPITest.m
  ios/PurchasesHybridCommon/PurchasesHybridCommon.xcodeproj/project.pbxproj
  ios/PurchasesHybridCommon/PurchasesHybridCommon/PaywallProxy.swift
  ios/PurchasesHybridCommon/PurchasesHybridCommon/PaywallResult.swift
Labels: RevenueCatUI

#634 Add `PAYWALL_RESULT` to typescript enums
  typescript/src/enums.ts
Labels: RevenueCatUI

#636 Add API tests for paywall result enum in typescript
  typescript/apitesters/enums.ts
Labels: RevenueCatUI

#635 Release/8.10.0-beta.9
  .version
  CHANGELOG.latest.md
  CHANGELOG.md
  PurchasesHybridCommon.podspec
  android/gradle.properties
  typescript/package.json
Labels: next_release

#637 Do not update hybrids automatically on prereleases
  fastlane/Fastfile
Labels: ci

#638 Don't trigger updates on dependents on non-stable releases
  .circleci/config.yml
  fastlane/Fastfile
Labels: ci

#639 Fix paywall result not being returned
  android/hybridcommon-ui/src/main/java/com/revenuecat/purchases/hybridcommon/ui/PaywallFragment.kt
  ios/PurchasesHybridCommon/PurchasesHybridCommon/PaywallProxy.swift
Labels: RevenueCatUI

#642 Update paywalls with 6441719
  .lefthook/pre-push/detekt.sh
  CHANGELOG.md
  DEVELOPMENT.md
  Gemfile
  Gemfile.lock
  PurchasesHybridCommon.podspec
  ios/PurchasesHybridCommon/Podfile
  lefthook.yml
Labels: RevenueCatUI

#643 Release 8.10.0-beta.10
  .version
  CHANGELOG.latest.md
  CHANGELOG.md
  PurchasesHybridCommon.podspec
  android/gradle.properties
  typescript/package.json
Labels: RevenueCatUI

#644 Add paywallViewControlleSizeDidChange to PaywallProxy
  ios/PurchasesHybridCommon/PurchasesHybridCommon/PaywallProxy.swift
Labels: RevenueCatUI

#649 Release/8.10.0
  .version
  CHANGELOG.latest.md
  CHANGELOG.md
  PurchasesHybridCommon.podspec
  android/gradle.properties
  ios/PurchasesHybridCommon/Info.plist
  ios/PurchasesHybridCommon/PurchasesHybridCommonTests/Info.plist
  typescript/package.json
Labels: next_release

#650 Update fastlane internal plugin
  Gemfile.lock
Labels: ci

#652 Fix update native versions job after hybrid common android split
  fastlane/Fastfile
Labels: ci

#656 `Paywalls`: fix `UIApplication.keyWindow` deprecation warning
  ios/PurchasesHybridCommon/PurchasesHybridCommon/PaywallProxy.swift
Labels: RevenueCatUI

#664 Fix `stable-release-tags` filter in config.yaml
  .circleci/config.yml
Labels: ci

#665 `CircleCI`: change jobs to use Apple Silicon
  .circleci/config.yml
Labels: ci

#667 Fix getting `rootViewController`
  ios/PurchasesHybridCommon/PurchasesHybridCommon/PaywallProxy.swift
Labels: RevenueCatUI

#669 Update Android orb
  .circleci/config.yml
Labels: ci

#675 `Paywalls`: add methods for presenting paywalls with an offering identifier (iOS)
  ios/PurchasesHybridCommon/ObjCAPITester/RCPaywallProxyAPITest.m
  ios/PurchasesHybridCommon/PurchasesHybridCommon/PaywallProxy.swift
Labels: RevenueCatUI

#670 `Paywalls`: add methods for presenting paywalls with an offering identifier (Android)
  android/hybridcommon-ui/src/main/java/com/revenuecat/purchases/hybridcommon/ui/PaywallFragment.kt
  android/hybridcommon-ui/src/main/java/com/revenuecat/purchases/hybridcommon/ui/PaywallHelpers.kt
  android/hybridcommon-ui/src/main/java/com/revenuecat/purchases/hybridcommon/ui/PaywallSource.kt
Labels: feat, RevenueCatUI

#679 `CircleCI`: don't skip major bumps
  fastlane/Fastfile
Labels: ci

#685 `CommonFunctionality`: `purchase` methods also return `StoreTransaction`
  ios/PurchasesHybridCommon/PurchasesHybridCommon/CommonFunctionality.swift
  ios/PurchasesHybridCommon/PurchasesHybridCommonIntegrationTests/__Snapshots__/StoreKitIntegrationTests/SK1-testCanPurchasePackage.1.json
  ios/PurchasesHybridCommon/PurchasesHybridCommonIntegrationTests/__Snapshots__/StoreKitIntegrationTests/SK1-testCanPurchaseProduct.1.json
  ios/PurchasesHybridCommon/PurchasesHybridCommonIntegrationTests/__Snapshots__/StoreKitIntegrationTests/SK2-testCanPurchasePackage.1.json
  ios/PurchasesHybridCommon/PurchasesHybridCommonIntegrationTests/__Snapshots__/StoreKitIntegrationTests/SK2-testCanPurchaseProduct.1.json
Labels: feat

#690 `MakePurchaseResult`: added transaction
  typescript/src/callbackTypes.ts
Labels: feat

#700 Add support for `visionOS`
  .circleci/config.yml
  PurchasesHybridCommon.podspec
  PurchasesHybridCommonUI.podspec
  fastlane/Fastfile
Labels: feat
