Repository RevenueCat/purchases-hybrid-common, pull requests merged in 2024-07, with the labels that each got.

#851 Bump Android 7.12.0
  android/gradle/libs.versions.toml
  android/hybridcommon/src/test/java/com/revenuecat/purchases/hybridcommon/CommonKtTests.kt
Labels: dependencies

#854 Add `DEFERRED` to typescript enum
  typescript/api-report/purchases-typescript-internal.api.md
  typescript/src/offerings.ts
Labels: refactor

#859 Update Android to v8 of the native SDK
  android/api-tests/src/test/java/com/revenuecat/apitests/java/CommonApiTests.java
  android/api-tests/src/test/java/com/revenuecat/apitests/kotlin/CommonApiTests.kt
  android/gradle/libs.versions.toml
  android/hybridcommon/build.gradle.kts
  android/hybridcommon/config/detekt/detekt-baseline.xml
  android/hybridcommon/src/main/java/com/revenuecat/purchases/hybridcommon/common.kt
  android/hybridcommon/src/main/java/com/revenuecat/purchases/hybridcommon/mappers/StoreProductMapper.kt
  android/hybridcommon/src/test/java/com/revenuecat/purchases/hybridcommon/CommonKtTests.kt
  android/hybridcommon/src/test/java/com/revenuecat/purchases/hybridcommon/ConfiguringUnitTests.kt
  ios/PurchasesHybridCommon/PurchasesHybridCommon/CommonFunctionality.swift
  ios/PurchasesHybridCommon/PurchasesHybridCommon/Purchases+HybridAdditions.swift
  ios/PurchasesHybridCommon/PurchasesHybridCommonIntegrationTests/BaseIntegrationTests.swift
  ios/PurchasesHybridCommon/PurchasesHybridCommonTests/PurchasesHybridAdditionsTests.swift
  typescript/api-report/purchases-typescript-internal.api.md
  typescript/src/enums.ts
  typescript/src/offerings.ts
  typescript/src/purchasesConfiguration.ts
Labels: breaking

#621 add pricePerPeriod properties
  android/hybridcommon/src/main/java/com/revenuecat/purchases/hybridcommon/mappers/StoreProductMapper.kt
  android/hybridcommon/src/test/java/com/revenuecat/purchases/hybridcommon/mappers/StoreProductMapperTests.kt
  ios/PurchasesHybridCommon/PurchasesHybridCommon/StoreProduct+HybridAdditions.swift
  ios/PurchasesHybridCommon/PurchasesHybridCommonIntegrationTests/__Snapshots__/StoreKitIntegrationTests/SK1-testCanGetOfferings.1.json
  ios/PurchasesHybridCommon/PurchasesHybridCommonIntegrationTests/__Snapshots__/StoreKitIntegrationTests/SK2-testCanGetOfferings.1.json
  typescript/api-report/purchases-typescript-internal.api.md
  typescript/src/offerings.ts
Labels: feat

#858 adopt purchases-ios 5.2.2
  .circleci/config.yml
  PurchasesHybridCommon.podspec
  PurchasesHybridCommonUI.podspec
  android/api-tests/src/test/java/com/revenuecat/apitests/kotlin/CommonApiTests.kt
  android/hybridcommon/src/main/java/com/revenuecat/purchases/hybridcommon/common.kt
  ios/PurchasesHybridCommon/ObjCAPITester/RCHybridCommonAPITest.m
  ios/PurchasesHybridCommon/ObjCAPITester/RCPurchases+HybridAdditionsAPITest.m
  ios/PurchasesHybridCommon/Podfile
  ios/PurchasesHybridCommon/Podfile.lock
  ios/PurchasesHybridCommon/PurchasesHybridCommon.xcodeproj/project.pbxproj
  ios/PurchasesHybridCommon/PurchasesHybridCommon/CommonFunctionality.swift
  ios/PurchasesHybridCommon/PurchasesHybridCommon/EntitlementInfo+HybridAdditions.swift
  ios/PurchasesHybridCommon/PurchasesHybridCommon/EntitlementInfos+HybridAdditions.swift
  ios/PurchasesHybridCommon/PurchasesHybridCommon/NSDate+HybridAdditions.swift
  ios/PurchasesHybridCommon/PurchasesHybridCommon/Purchases+HybridAdditions.swift
  ios/PurchasesHybridCommon/PurchasesHybridCommon/PurchasesAreCompletedBy+HybridAdditions.swift
  ios/PurchasesHybridCommon/PurchasesHybridCommon/StoreKitVersion+HybridAdditions.swift
  ios/PurchasesHybridCommon/PurchasesHybridCommon/StoreProduct+HybridAdditions.swift
  ios/PurchasesHybridCommon/PurchasesHybridCommon/StoreProductDiscount+HybridAdditions.swift
  ios/PurchasesHybridCommon/PurchasesHybridCommonIntegrationTests/BaseIntegrationTests.swift
  ios/PurchasesHybridCommon/PurchasesHybridCommonIntegrationTests/StoreKitIntegrationTests.swift
  ios/PurchasesHybridCommon/PurchasesHybridCommonIntegrationTests/__Snapshots__/StoreKitIntegrationTests/SK2-testCanPurchasePackage.1.json
  ios/PurchasesHybridCommon/PurchasesHybridCommonIntegrationTests/__Snapshots__/StoreKitIntegrationTests/SK2-testCanPurchaseProduct.1.json
  ios/PurchasesHybridCommon/PurchasesHybridCommonIntegrationTests/__Snapshots__/StoreKitIntegrationTests/SK2-testLogInAndLogOut.1.json
  ios/PurchasesHybridCommon/PurchasesHybridCommonIntegrationTests/__Snapshots__/StoreKitIntegrationTests/SK2-testRecordPurchase.1.json
  ios/PurchasesHybridCommon/PurchasesHybridCommonTests/Mocks/MockPurchases.swift
  ios/PurchasesHybridCommon/PurchasesHybridCommonTests/PurchasesAreCompletedByHybridAdditionsTests.swift
  ios/PurchasesHybridCommon/PurchasesHybridCommonTests/PurchasesHybridAdditionsTests.swift
  ios/PurchasesHybridCommon/PurchasesHybridCommonTests/PurchasesHybridCommonTests.swift
  ios/PurchasesHybridCommon/PurchasesHybridCommonTests/StoreKitVersionHybridAdditionsTests.swift
  ios/PurchasesHybridCommon/PurchasesHybridCommonTests/XCTestCase+Expectations.swift
  typescript/api-report/purchases-typescript-internal.api.md
  typescript/src/enums.ts
  typescript/src/purchasesConfiguration.ts
Labels: next_release, feat

#884 Require STOREKIT_VERSION when PURCHASES_ARE_COMPLETED_BY is MY_APP
  typescript/api-report/purchases-typescript-internal.api.md
  typescript/src/enums.ts
  typescript/src/purchasesConfiguration.ts
Labels: breaking, feat
