Repository RevenueCat/purchases-hybrid-common, pull requests merged in 2024-08, with the labels that each got.

#886 Release/13.0.0
  .version
  CHANGELOG.latest.md
  CHANGELOG.md
  PurchasesHybridCommon.podspec
  PurchasesHybridCommonUI.podspec
  android/gradle.properties
  ios/PurchasesHybridCommon/Info.plist
  ios/PurchasesHybridCommon/PurchasesHybridCommon/Constants.swift
  ios/PurchasesHybridCommon/PurchasesHybridCommonTests/Info.plist
  typescript/package.json
Labels: next_release

#894 StoreKitVersion Docstring Typo Fix
  typescript/src/enums.ts
Labels: documentation, docs

#903 iOS 5.2.3 => 5.3.0 Android 8.4.0 => 8.6.0
  PurchasesHybridCommon.podspec
  PurchasesHybridCommonUI.podspec
  android/gradle/libs.versions.toml
  ios/PurchasesHybridCommon/Podfile
  ios/PurchasesHybridCommon/Podfile.lock
Labels: dependencies, minor
