Repository RevenueCat/purchases-hybrid-common, pull requests merged in 2024-11, with the labels that each got.

#969 Syncs version in `Package.swift` and `Package.resolved` with other iOS version files
  Package.resolved
  Package.swift
Labels: pr:other

#970 [AUTOMATIC] iOS 5.8.0 => 5.10.0
  Package.resolved
  Package.swift
  PurchasesHybridCommon.podspec
  PurchasesHybridCommonUI.podspec
  ios/PurchasesHybridCommon/Podfile
  ios/PurchasesHybridCommon/Podfile.lock
  ios/PurchasesHybridCommon/PurchasesHybridCommonTests/Mocks/MockPurchases.swift
Labels: pr:dependencies, pr:force_minor

#968 Expose fetching & redeeming win-backs on custom paywalls to hybrids
  DEVELOPMENT.md
  ios/PurchasesHybridCommon/ObjCAPITester/RCHybridCommonAPITest.m
  ios/PurchasesHybridCommon/PurchasesHybridCommon.xcodeproj/project.pbxproj
  ios/PurchasesHybridCommon/PurchasesHybridCommon/CommonFunctionality.swift
  ios/PurchasesHybridCommon/PurchasesHybridCommon/WinBackOffer+HybridAdditions.swift
  typescript/api-report/purchases-typescript-internal.api.md
  typescript/src/offerings.ts
Labels: pr:feat

#973 [AUTOMATIC] iOS 5.10.0 => 5.12.0
  Package.resolved
  Package.swift
  PurchasesHybridCommon.podspec
  PurchasesHybridCommonUI.podspec
  ios/PurchasesHybridCommon/Podfile
  ios/PurchasesHybridCommon/Podfile.lock
  ios/PurchasesHybridCommon/PurchasesHybridCommonTests/Mocks/MockPurchases.swift
Labels: pr:dependencies, pr:force_minor

#974 Add methods to set Tenjin and Kochava integration IDs
  android/api-tests/src/test/java/com/revenuecat/apitests/java/SubscriberAttributesApiTests.java
  android/api-tests/src/test/java/com/revenuecat/apitests/kotlin/SubscriberAttributesApiTests.kt
  android/hybridcommon/src/main/java/com/revenuecat/purchases/hybridcommon/subscriberAttributes.kt
  ios/PurchasesHybridCommon/ObjCAPITester/RCHybridCommonAPITest.m
  ios/PurchasesHybridCommon/PurchasesHybridCommon/CommonFunctionality.swift
Labels: pr:feat
