Repository RevenueCat/purchases-hybrid-common, pull requests merged in 2024-02, with the labels that each got.

#704 Create PaywallListenerWrapper and expose mappers
  android/hybridcommon-ui/build.gradle.kts
  android/hybridcommon-ui/src/main/java/com/revenuecat/purchases/hybridcommon/ui/PaywallListenerWrapper.kt
  android/hybridcommon/src/main/java/com/revenuecat/purchases/hybridcommon/common.kt
  android/hybridcommon/src/main/java/com/revenuecat/purchases/hybridcommon/mappers/OfferingsMapper.kt
  android/hybridcommon/src/main/java/com/revenuecat/purchases/hybridcommon/mappers/PurchasesError.kt
  android/hybridcommon/src/test/java/com/revenuecat/purchases/hybridcommon/MappersTests.kt
Labels: feat

#708 Bump android to 6.9.6
  android/build.gradle
Labels: dependencies

#706 Add PaywallViewControllerDelegateWrapper
  PurchasesHybridCommonUI.podspec
  fastlane/Fastfile
  ios/PurchasesHybridCommon/Podfile
  ios/PurchasesHybridCommon/Podfile.lock
  ios/PurchasesHybridCommon/PurchasesHybridCommon.xcodeproj/project.pbxproj
  ios/PurchasesHybridCommon/PurchasesHybridCommon/CustomerInfo+HybridAdditions.swift
  ios/PurchasesHybridCommon/PurchasesHybridCommon/StoreTransaction+HybridAdditions.swift
  ios/PurchasesHybridCommon/PurchasesHybridCommonUI/PaywallProxy.swift
  ios/PurchasesHybridCommon/PurchasesHybridCommonUI/PaywallViewControllerDelegateWrapper.swift
Labels: feat

#718 `PurchasesHybridCommon.podspec`: remove `SwiftUI` dependency
  PurchasesHybridCommon.podspec
Labels: build

#724 Set delegate for PaywallViewController
  ios/PurchasesHybridCommon/PurchasesHybridCommonUI/PaywallProxy.swift
Labels: fix

#725 Add `paywallViewControllerDidStartPurchase` to wrapper delegate
  ios/PurchasesHybridCommon/PurchasesHybridCommonUI/PaywallProxy.swift
  ios/PurchasesHybridCommon/PurchasesHybridCommonUI/PaywallViewControllerDelegateWrapper.swift
Labels: feat

#729 Add lanes to trigger dependency updates and bump
  Gemfile
  Gemfile.lock
  fastlane/Fastfile
  fastlane/README.md
Labels: ci

#735 Add `didStartPurchaseWithPackage`
  ios/PurchasesHybridCommon/PurchasesHybridCommon/Package+HybridAdditions.swift
  ios/PurchasesHybridCommon/PurchasesHybridCommonUI/PaywallProxy.swift
  ios/PurchasesHybridCommon/PurchasesHybridCommonUI/PaywallViewControllerDelegateWrapper.swift
Labels: feat

#734 Add `didStartRestore`
  ios/PurchasesHybridCommon/PurchasesHybridCommonUI/PaywallProxy.swift
  ios/PurchasesHybridCommon/PurchasesHybridCommonUI/PaywallViewControllerDelegateWrapper.swift
Labels: feat
