Repository RevenueCat/purchases-hybrid-common, pull requests merged in 2024-03, with the labels that each got.

#755 Update CHANGELOG.md
  CHANGELOG.md
Labels: docs

#757 Update RELEASING.md
  RELEASING.md
Labels: docs

#759 Fix revision type in PresentedOfferingTargetingContext context and add API testers
  typescript/apitesters/offerings.ts
  typescript/src/offerings.ts
Labels: feat

#746 Add `paywallViewControllerRequestedDismissal`
  ios/PurchasesHybridCommon/PurchasesHybridCommonUI/PaywallProxy.swift
  ios/PurchasesHybridCommon/PurchasesHybridCommonUI/PaywallViewControllerDelegateWrapper.swift
Labels: feat

#769 Add font support to presentPaywall
  android/hybridcommon-ui/src/main/java/com/revenuecat/purchases/hybridcommon/ui/PaywallFragment.kt
  android/hybridcommon-ui/src/main/java/com/revenuecat/purchases/hybridcommon/ui/PaywallHelpers.kt
  ios/PurchasesHybridCommon/PurchasesHybridCommonUI/PaywallProxy.swift
Labels: feat

#774 Fix compilation in xcode 14 (Swift 5.8)
  ios/PurchasesHybridCommon/PurchasesHybridCommonUI/PaywallProxy.swift
Labels: fix

#773 Add `RC_BILLING` store
  ios/PurchasesHybridCommon/PurchasesHybridCommon/EntitlementInfo+HybridAdditions.swift
  typescript/src/customerInfo.ts
Labels: HOLD, refactor
