Repository RevenueCat/purchases-hybrid-common, pull requests merged in 2025-03, with the labels that each got.

#1065 [EXTERNAL] feat(ios): expose showManageSubscriptions (#1064) by @dylancom
  ios/PurchasesHybridCommon/PurchasesHybridCommon/CommonFunctionality.swift
Labels: pr:feat

#1067 Add `subscriptionsByProductIdentifier` map of SubscriptionInfo by productId to CustomerInfo
  android/hybridcommon/src/main/java/com/revenuecat/purchases/hybridcommon/mappers/CustomerInfoMapper.kt
  android/hybridcommon/src/main/java/com/revenuecat/purchases/hybridcommon/mappers/SubscriptionInfoMapper.kt
  android/hybridcommon/src/test/java/com/revenuecat/purchases/hybridcommon/CustomerInfoMappersTests.kt
  ios/PurchasesHybridCommon/PurchasesHybridCommon.xcodeproj/project.pbxproj
  ios/PurchasesHybridCommon/PurchasesHybridCommon/CustomerInfo+HybridAdditions.swift
  ios/PurchasesHybridCommon/PurchasesHybridCommon/EntitlementInfo+HybridAdditions.swift
  ios/PurchasesHybridCommon/PurchasesHybridCommon/Enums+HybridAdditions.swift
  ios/PurchasesHybridCommon/PurchasesHybridCommon/SubscriptionInfo+HybridAdditions.swift
  ios/PurchasesHybridCommon/PurchasesHybridCommonIntegrationTests/__Snapshots__/StoreKitIntegrationTests/SK1-testCanPurchasePackage.1.json
  ios/PurchasesHybridCommon/PurchasesHybridCommonIntegrationTests/__Snapshots__/StoreKitIntegrationTests/SK1-testCanPurchaseProduct.1.json
  ios/PurchasesHybridCommon/PurchasesHybridCommonIntegrationTests/__Snapshots__/StoreKitIntegrationTests/SK1-testLogInAndLogOut.1.json
  ios/PurchasesHybridCommon/PurchasesHybridCommonIntegrationTests/__Snapshots__/StoreKitIntegrationTests/SK1-testLogInAndLogOut.2.json
  ios/PurchasesHybridCommon/PurchasesHybridCommonIntegrationTests/__Snapshots__/StoreKitIntegrationTests/SK2-testCanPurchasePackage.1.json
  ios/PurchasesHybridCommon/PurchasesHybridCommonIntegrationTests/__Snapshots__/StoreKitIntegrationTests/SK2-testCanPurchaseProduct.1.json
  ios/PurchasesHybridCommon/PurchasesHybridCommonIntegrationTests/__Snapshots__/StoreKitIntegrationTests/SK2-testLogInAndLogOut.1.json
  ios/PurchasesHybridCommon/PurchasesHybridCommonIntegrationTests/__Snapshots__/StoreKitIntegrationTests/SK2-testLogInAndLogOut.2.json
  typescript/api-report/purchases-typescript-internal.api.md
  typescript/src/customerInfo.ts
Labels: pr:feat

#1072 Add `subscriptionsByProductIdentifier` to CustomerInfo
  typescript/api-report/purchases-typescript-internal.api.md
  typescript/src/customerInfo.ts
Labels: pr:fix

#1078 Update detekt and enable autocorrect
  android/gradle/libs.versions.toml
  android/hybridcommon-ui/build.gradle.kts
  android/hybridcommon/build.gradle.kts
Labels: pr:other

#1079 feat: Add missing onCloseHandler to CustomerCenterUIViewController for custom close
  ios/PurchasesHybridCommon/Podfile
  ios/PurchasesHybridCommon/Podfile.lock
  ios/PurchasesHybridCommon/PurchasesHybridCommonUI/CustomerCenter/CustomerCenterProxy.swift
  ios/PurchasesHybridCommon/PurchasesHybridCommonUI/CustomerCenter/CustomerCenterUIViewController.swift
  ios/PurchasesHybridCommon/PurchasesHybridCommonUI/CustomerCenter/CustomerCenterViewControllerDelegateWrapper.swift
Labels: pr:feat

#1081 chore: test pod_push_with_error_handling for new pods
  fastlane/Fastfile
Labels: enhancement, pr:other

#1076 Create `CustomerCenterListenerWrapper`
  android/api-tests/src/test/java/com/revenuecat/apitests/kotlin/PaywallApiTests.kt
  android/hybridcommon-ui/src/main/java/com/revenuecat/purchases/hybridcommon/ui/CustomerCenterListenerWrapper.kt
  android/hybridcommon-ui/src/main/java/com/revenuecat/purchases/hybridcommon/ui/PaywallFragment.kt
  android/hybridcommon-ui/src/main/java/com/revenuecat/purchases/hybridcommon/ui/PaywallHelpers.kt
  android/hybridcommon-ui/src/main/java/com/revenuecat/purchases/hybridcommon/ui/PaywallListenerWrapper.kt
  android/hybridcommon-ui/src/main/java/com/revenuecat/purchases/hybridcommon/ui/PaywallResultExtensions.kt
  android/hybridcommon-ui/src/main/java/com/revenuecat/purchases/hybridcommon/ui/PaywallResultListener.kt
Labels: pr:feat

#1077 Add automatic changes on `.idea` files
  .idea/.gitignore
  android/.idea/compiler.xml
  android/.idea/gradle.xml
  android/.idea/misc.xml
  android/.idea/runConfigurations.xml
Labels: pr:other

#1084 Add more events to iOS `CustomerCenterViewControllerDelegateWrapper`
  Package.resolved
  Package.swift
  PurchasesHybridCommon.podspec
  PurchasesHybridCommonUI.podspec
  android/gradle/libs.versions.toml
  android/hybridcommon-ui/src/main/java/com/revenuecat/purchases/hybridcommon/ui/CustomerCenterListenerWrapper.kt
  ios/PurchasesHybridCommon/Podfile
  ios/PurchasesHybridCommon/Podfile.lock
  ios/PurchasesHybridCommon/PurchasesHybridCommon.xcodeproj/project.pbxproj
  ios/PurchasesHybridCommon/PurchasesHybridCommon/RefundRequestStatus+HybridAdditions.swift
  ios/PurchasesHybridCommon/PurchasesHybridCommonUI/CustomerCenter/CustomerCenterProxy.swift
  ios/PurchasesHybridCommon/PurchasesHybridCommonUI/CustomerCenter/CustomerCenterUIViewController.swift
  ios/PurchasesHybridCommon/PurchasesHybridCommonUI/CustomerCenter/CustomerCenterViewControllerDelegateWrapper.swift
Labels: pr:feat

#1100 Expose Virtual Currency Balances
  Package.swift
  PurchasesHybridCommon.podspec
  PurchasesHybridCommonUI.podspec
  android/api-tests/src/test/java/com/revenuecat/apitests/kotlin/mappers/VirtualCurrencyInfoMapperApiTests.kt
  android/gradle/libs.versions.toml
  android/hybridcommon/src/main/java/com/revenuecat/purchases/hybridcommon/mappers/CustomerInfoMapper.kt
  android/hybridcommon/src/main/java/com/revenuecat/purchases/hybridcommon/mappers/VirtualCurrencyInfoMapper.kt
  android/hybridcommon/src/test/java/com/revenuecat/purchases/hybridcommon/CustomerInfoMappersTests.kt
  android/hybridcommon/src/test/java/com/revenuecat/purchases/hybridcommon/mappers/VirtualCurrencyInfoMapperTests.kt
  ios/PurchasesHybridCommon/Podfile
  ios/PurchasesHybridCommon/Podfile.lock
  ios/PurchasesHybridCommon/PurchasesHybridCommon.xcodeproj/project.pbxproj
  ios/PurchasesHybridCommon/PurchasesHybridCommon/CustomerInfo+HybridAdditions.swift
  ios/PurchasesHybridCommon/PurchasesHybridCommon/VirtualCurrencyInfo+HybridAdditions.swift
  ios/PurchasesHybridCommon/PurchasesHybridCommonIntegrationTests/__Snapshots__/StoreKitIntegrationTests/SK1-testCanPurchasePackage.1.json
  ios/PurchasesHybridCommon/PurchasesHybridCommonIntegrationTests/__Snapshots__/StoreKitIntegrationTests/SK1-testCanPurchaseProduct.1.json
  ios/PurchasesHybridCommon/PurchasesHybridCommonIntegrationTests/__Snapshots__/StoreKitIntegrationTests/SK1-testLogInAndLogOut.1.json
  ios/PurchasesHybridCommon/PurchasesHybridCommonIntegrationTests/__Snapshots__/StoreKitIntegrationTests/SK1-testLogInAndLogOut.2.json
  ios/PurchasesHybridCommon/PurchasesHybridCommonIntegrationTests/__Snapshots__/StoreKitIntegrationTests/SK2-testCanPurchasePackage.1.json
  ios/PurchasesHybridCommon/PurchasesHybridCommonIntegrationTests/__Snapshots__/StoreKitIntegrationTests/SK2-testCanPurchaseProduct.1.json
  ios/PurchasesHybridCommon/PurchasesHybridCommonIntegrationTests/__Snapshots__/StoreKitIntegrationTests/SK2-testLogInAndLogOut.1.json
  ios/PurchasesHybridCommon/PurchasesHybridCommonIntegrationTests/__Snapshots__/StoreKitIntegrationTests/SK2-testLogInAndLogOut.2.json
  ios/PurchasesHybridCommon/PurchasesHybridCommonTests/CustomerInfo+HybridAdditionsTests.swift
  ios/PurchasesHybridCommon/PurchasesHybridCommonTests/VirtualCurrencyInfo+HybridAdditionsTests.swift
  typescript/api-report/purchases-typescript-internal.api.md
  typescript/src/customerInfo.ts
Labels: pr:feat
