Repository RevenueCat/purchases-hybrid-common, pull requests merged in 2025-09, with the labels that each got.

#1261 Add `PaywallSource` with `PresentedOfferingContext` in Android
  android/api-tests/src/test/java/com/revenuecat/apitests/java/PaywallApiTests.java
  android/api-tests/src/test/java/com/revenuecat/apitests/kotlin/PaywallApiTests.kt
  android/hybridcommon-ui/src/main/java/com/revenuecat/purchases/hybridcommon/ui/PaywallFragment.kt
  android/hybridcommon-ui/src/main/java/com/revenuecat/purchases/hybridcommon/ui/PaywallSource.kt
Labels: pr:feat, pr:RevenueCatUI, feat:PaywallV2

#1268 Add internal `_purchaseSimulatedStorePackage`
  purchases-js-hybrid-mappings/src/purchases-common.ts
Labels: pr:other

#1274 Use `preferredUILocaleOverride` name in `PurchasesConfiguration`
  typescript/api-report/purchases-typescript-internal.api.md
  typescript/src/purchasesConfiguration.ts
Labels: pr:fix

#1286 Implement setLogHandler for web
  Gemfile.lock
  purchases-js-hybrid-mappings/api-report/api.json
  purchases-js-hybrid-mappings/api-report/purchases-js-hybrid-mappings.api.md
  purchases-js-hybrid-mappings/package.json
  purchases-js-hybrid-mappings/src/purchases-common.ts
  purchases-js-hybrid-mappings/tests/purchases-common.test.ts
Labels: pr:feat

#1303 [v14] Bump fastlane-plugin-revenuecat_internal from `9a29f63` to `e1c0e04`
  Gemfile.lock
Labels: pr:other

#1308 Update changelog for release v14.3.0
  CHANGELOG.md
Labels: pr:other
