Repository RevenueCat/purchases-hybrid-common, pull requests merged in 2025-01, with the labels that each got.

#1004 Add `parseAsWebPurchaseRedemption` API to iOS
  ios/PurchasesHybridCommon/PurchasesHybridCommon/CommonFunctionality.swift
Labels: pr:feat

#1016 Dismiss PaywallFragment after PaywallActivity is dismissed
  android/hybridcommon-ui/src/main/java/com/revenuecat/purchases/hybridcommon/ui/PaywallFragment.kt
Labels: pr:fix

#1008 Introduce IOSAPIAvailabilityChecker for KMP
  ios/PurchasesHybridCommon/PurchasesHybridCommon.xcodeproj/project.pbxproj
  ios/PurchasesHybridCommon/PurchasesHybridCommon/IOSAPIAvailabilityChecker.swift
Labels: pr:other

#1026 Adds API availability check for `enableAdServicesAttributionTokenCollection()`
  ios/PurchasesHybridCommon/PurchasesHybridCommon/IOSAPIAvailabilityChecker.swift
Labels: pr:other

#1028 Expose iOS PurchaseParamsBuilder API to KMP
  ios/PurchasesHybridCommon/PurchasesHybridCommon.xcodeproj/project.pbxproj
  ios/PurchasesHybridCommon/PurchasesHybridCommon/PurchaseParamsBuilder+HybridExtensions.swift
Labels: pr:fix, pr:other

#1030 [CI] Remove requirement for pod push to succeed to continue release process
  .circleci/config.yml
Labels: pr:other

#1031 Import foundation in IOSAPIAvailabilityChecker
  ios/PurchasesHybridCommon/PurchasesHybridCommon/IOSAPIAvailabilityChecker.swift
Labels: pr:fix
