Repository RevenueCat/purchases-hybrid-common, pull requests merged in 2025-07, with the labels that each got.

#1182 Migrates publishing to Maven Central Portal.
  android/gradle.properties
  android/gradle/libs.versions.toml
  fastlane/Fastfile
Labels: pr:other

#1184 Adds the correct environment variables to `deploy-android`
  .circleci/config.yml
Labels: pr:other, pr:force_patch

#1173 Update PHC with iOS VC Updates
  ios/PurchasesHybridCommon/ObjCAPITester/RCHybridCommonAPITest.m
  ios/PurchasesHybridCommon/PurchasesHybridCommon.xcodeproj/project.pbxproj
  ios/PurchasesHybridCommon/PurchasesHybridCommon/CommonFunctionality.swift
  ios/PurchasesHybridCommon/PurchasesHybridCommon/VirtualCurrencies+HybridAdditions.swift
  ios/PurchasesHybridCommon/PurchasesHybridCommon/VirtualCurrency+HybridAdditions.swift
  ios/PurchasesHybridCommon/PurchasesHybridCommonTests/Mocks/MockPurchases.swift
  ios/PurchasesHybridCommon/PurchasesHybridCommonTests/PurchasesHybridCommonTests.swift
  ios/PurchasesHybridCommon/PurchasesHybridCommonTests/VirtualCurrencies+HybridAdditionsTests.swift
  ios/PurchasesHybridCommon/PurchasesHybridCommonTests/VirtualCurrency+HybridAdditionsTests.swift
  typescript/api-report/purchases-typescript-internal.api.md
  typescript/src/index.ts
  typescript/src/virtualCurrency.ts
Labels: pr:feat

#1190 Fix clear background of paywalls in iOS
  ios/PurchasesHybridCommon/PurchasesHybridCommonUI/Paywalls/PaywallProxy.swift
Labels: pr:fix, pr:RevenueCatUI

#1192 Update Kotlin 2.0.21 while keeping language compatibility
  android/gradle/libs.versions.toml
  android/hybridcommon-ui/build.gradle.kts
  android/hybridcommon/build.gradle.kts
Labels: pr:breaking, pr:other

#1204 Use spi(Interal) Import RC in Tests
  ios/PurchasesHybridCommon/PurchasesHybridCommonTests/PurchasesHybridCommonTests.swift
  ios/PurchasesHybridCommon/PurchasesHybridCommonTests/VirtualCurrencies+HybridAdditionsTests.swift
  ios/PurchasesHybridCommon/PurchasesHybridCommonTests/VirtualCurrency+HybridAdditionsTests.swift
Labels: pr:fix

#1201 Auto dismiss paywall for required entitlement
  ios/PurchasesHybridCommon/PurchasesHybridCommonUI/Paywalls/PaywallProxy.swift
Labels: pr:fix

#1222 feat: add setPostHogUserId method
  android/api-tests/src/test/java/com/revenuecat/apitests/java/SubscriberAttributesApiTests.java
  android/api-tests/src/test/java/com/revenuecat/apitests/kotlin/SubscriberAttributesApiTests.kt
  android/hybridcommon/src/main/java/com/revenuecat/purchases/hybridcommon/subscriberAttributes.kt
  ios/PurchasesHybridCommon/ObjCAPITester/RCHybridCommonAPITest.m
  ios/PurchasesHybridCommon/PurchasesHybridCommon/CommonFunctionality.swift
  ios/PurchasesHybridCommon/PurchasesHybridCommonTests/Mocks/MockPurchases.swift
Labels: pr:feat
