Repository RevenueCat/purchases-hybrid-common, pull requests merged in 2025-02, with the labels that each got.

#1037 Adds `IntroEligibility` to public API surface
  ios/PurchasesHybridCommon/PurchasesHybridCommon.xcodeproj/project.pbxproj
  ios/PurchasesHybridCommon/PurchasesHybridCommon/IntroEligibility+HybridExtensions.swift
Labels: pr:other, pr:force_patch

#1046 feat: Introduce CustomerCenterProxy
  ios/PurchasesHybridCommon/PurchasesHybridCommon.xcodeproj/project.pbxproj
  ios/PurchasesHybridCommon/PurchasesHybridCommonUI/CustomerCenter/CustomerCenterProxy.swift
  ios/PurchasesHybridCommon/PurchasesHybridCommonUI/CustomerCenter/CustomerCenterUIViewController.swift
  ios/PurchasesHybridCommon/PurchasesHybridCommonUI/CustomerCenter/CustomerCenterViewControllerDelegateWrapper.swift
  ios/PurchasesHybridCommon/PurchasesHybridCommonUI/Paywalls/PaywallProxy.swift
  ios/PurchasesHybridCommon/PurchasesHybridCommonUI/Paywalls/PaywallResult.swift
  ios/PurchasesHybridCommon/PurchasesHybridCommonUI/Paywalls/PaywallViewControllerDelegateWrapper.swift
Labels: pr:feat, pr:RevenueCatUI

#1059 Revert "[AUTOMATIC] Release/13.20.0 (#1057)"
  .version
  CHANGELOG.latest.md
  CHANGELOG.md
  PurchasesHybridCommon.podspec
  PurchasesHybridCommonUI.podspec
  android/gradle.properties
  ios/PurchasesHybridCommon/Info.plist
  ios/PurchasesHybridCommon/PurchasesHybridCommon/Constants.swift
  ios/PurchasesHybridCommon/PurchasesHybridCommonTests/Info.plist
  typescript/package.json
Labels: pr:other

#1049 chore: Ignore idea caches
  .gitignore
Labels: enhancement, pr:other
